Controllers films users
sarcazmatic/java-filmorate pull request #2
Opened 2022-11-10 17:40 UTC by sarcazmatic

2022-11-10 20:54 UTC, Frilock requested changes
Еще пара комментариев

2022-11-10 20:54 UTC, Frilock commented on mvnw
> +# ----------------------------------------------------------------------------
Какой то странный файл .DS_Store, зачем он?

2022-11-10 20:54 UTC, Frilock commented on pom.xml
> +			<version>3.12.0</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${simple-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2022-11-10 20:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (StringUtils.isBlank(film.getName()) || StringUtils.isBlank(film.getDescription()) || StringUtils.length(film.getDescription()) > 200 || film.getReleaseDate().isBefore(CUT_OFF_DATE) || fil
Слишком длинная строчка, давайте данные проверки по одной разделим, ну то есть чтобы исключение было более понятным, чтобы была понятна причина того, что валидация не прошла

2022-11-10 20:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int id = 1;
Установите себе плагин в IDEA sonarlint - статический анализатор кода, подскажет ряд хороших практик. Идентификатор лучше статичным сделать

2022-11-10 20:54 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +public class FilmTest {
А почему только не успешные тесты? Давайте еще напишем ряд успешных, когда ошибок не возникает. Кроме того метод filmValidate должен быть приватным, а вы должны вызывать методы создания и обновления

2022-11-10 20:54 UTC, Frilock commented on src/main/resources/tests/package.json
> +{
А это Вам для чего?

2022-11-11 14:43 UTC, sarcazmatic commented on mvnw
> +# ----------------------------------------------------------------------------
Это файл файндера MacOS, добавил его в .gitignore

2022-11-11 14:47 UTC, sarcazmatic commented on pom.xml
> +			<version>3.12.0</version>
Принял, запомнил, поправил

2022-11-11 15:39 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (StringUtils.isBlank(film.getName()) || StringUtils.isBlank(film.getDescription()) || StringUtils.length(film.getDescription()) > 200 || film.getReleaseDate().isBefore(CUT_OFF_DATE) || fil
разбил

2022-11-11 15:39 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int id = 1;
поставил, спасибо за рекомендацию

2022-11-11 18:35 UTC, sarcazmatic commented on src/main/resources/tests/package.json
> +{
Пробовал тест построить с файлом) убрал

2022-11-11 21:01 UTC, merged