feat: датабазы, жанры, mpa
sarcazmatic/java-filmorate pull request #3
Opened 2022-12-19 12:13 UTC by sarcazmatic

2022-12-19 15:29 UTC, sarcazmatic commented
325 тестов, Иван! 325!

2022-12-19 18:32 UTC, Frilock requested changes
Евгений, вижу Вы старались, сделали очень не тривиальное решение, за это Вам большой плюс.
 Однако, сделали довольно небрежно, довольно много ошибок по Code Style. Решение ходить в БД за id плохое, я такое не приму, поскольку при нагрузке вы получите огромные проблемы с производительность (как вариант решения, сделайте бин генератора, который будет увеличивать это поле, или просто в своих бинах storage классах сделайте статическое поле и увеличивайте когда Вам нужно, а лучше обратитесь к наставнику или коллегам, мб подскажут другое решение). 
Кроме того, сильно намудрили с сигнатурой классов модели и возвращаемым значением в контролере. В общем жду новую версию работы.

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre<Integer, String> {
Евгений, зачем вот это <Integer, String>?!! У Вас обычный класс.

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(Integer id, String name){
Можно поставить аннотацию AllArgsConstructror и убрать этот

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenresController.java
> +    public List<Genre<Integer, String>> getGenres() {
Зачем возвращать данные в таком странном формате ? Возвращайте просто List<Genre>

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenresController.java
> +        return List.copyOf(genresService.getGenres());
Зачем лишний раз копировать? Возвращайте то, что вернул метод getGenres

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenresController.java
> +
Лишняя пустая строчка

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +
Лишняя пустая строчка

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    public Mpa<String, Integer> getMpaById(@PathVariable Integer id) {
Аналогичные комментарии что и к прошлому контроллеру

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/DefaultDataException.java
> +    public DefaultDataException(String message) { super(message); }
Давайте форматирование поправим, чтобы выглядело как обычный метод, super на другой строке, } еще на другой

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration, int rate, List<User> likes, Mpa<String, Integer> mpa, List<Genre<Integer, String>> genres){
AllArgsConstructor и можно этот бурать

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setGenres(List<Genre<Integer, String>> genres) {
Это вроде обычные сеттеры, в Data есть Setter можно не писать обычные сеттеры

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    @Builder.Default private int id = 1;
private .... на новой строку

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa(String name, int id){
AllArgsConstructor, а вот @RequiredArgsConstructor - этот разве вам нужен?

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenresService.java
> +        return List.copyOf(genresStorage.getGenres());
Не нужно везде делать copyOf

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenresService.java
> +    public Genre<Integer, String> getGenreById(@PathVariable Integer id) {
@PathVariable - лишняя, это аннотация показывает, что из URL нужно взять параметр. Тут у Вас никакого URL нет

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    /*private void createAndAddFriend(int idHost, int idFriend) {
Закомментированный код нужно убрать.

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final Logger log = LoggerFactory.getLogger(UserDbStorage.class);
UserDbStorage.class - не тот класс в логгере (можно над классом Slf4j повесить и использовать логгер вместо этого)

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                filmRows.getDate("release_date").toLocalDate(),
filmRows.getDate("release_date") null не вернет? Иначе ошибка будет

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } else if (film.getReleaseDate().isBefore(CUT_OFF_DATE) || film.getReleaseDate() == null) {
film.getReleaseDate().isBefore(CUT_OFF_DATE) || film.getReleaseDate() == null нужно местами проверки поменять, иначе у вас возможна ошибка, поскольку слева на право проверка идет

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/genres/GenresDBStorage.java
> +    JdbcTemplate jdbcTemplate;
Модификатор потеряли

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/genres/GenresDBStorage.java
> +        if (id<=currentId()) {
Съехало форматирование, перед <= и после нужен пробел. Вообще Вы когда коммит делаете, в IDEA можно поставить галочку о том, чтобы происходило автоформатирование кода (позволит не следить за пробелами и оптимизацией импортов)

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/genres/GenresDBStorage.java
> +        if (id<=currentId()) {
Чтобы убрать лишнюю вложенность вы сначала проверяйте id <= currentId() {
throw ....
} 
другой код ...

Смысл надеюсь поняли

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("select MAX(film_id) as m from films;");
Идея делать дополнительный запрос в БД для того, чтобы узнать текущий ID максимально плохая, такое решение не правильное. Представьте когда объём запросов кратно вырастит, какие проблемы будут у Вас при нагрузке

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("select * from films as f LEFT OUTER JOIN ratings as r ON f.rating_id = r.rating_id WHERE f.title = ? GROUP BY f.film_id", film.getName());
Смотрите, вы где то пишите select, а где то DELETE, то есть у Вас ключевые слова где то то заглавными то строчными буквами. Приведите к одному формату

2022-12-19 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    JdbcTemplate jdbcTemplate;
Модификатор потеряли

2022-12-21 00:02 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/exception/DefaultDataException.java
> +    public DefaultDataException(String message) { super(message); }
Я это постоянно правлю, а потом все равно съезжает
Не понимаю, как это прекратить – гляну настройки идеи

2022-12-21 00:09 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                filmRows.getDate("release_date").toLocalDate(),
В конструкторе проставлены ограничения NonNull – я думал, это должно предупредить такие проблемцы

2022-12-21 00:27 UTC, sarcazmatic commented
В итоге помогли ребята с курса – замучился разбираться с автогенерацией ключей из таблиц.
Вопрос. Где почитать про ключи keyHolder и вот это и-фейс connection -> {
                PreparedStatement statement = connection.prepareStatement(sqlQueryPost, new String[]{"FILM_ID"});
                ...
                return statement;
            }, keyHolder)
Выглядит очень сложным. Что еще за стейтменты, как работает ифейс и как работает ки холдер.

2022-12-21 00:27 UTC, sarcazmatic commented
И да, прошлая версия была убитая – пардон, очень торопился

2022-12-21 00:28 UTC, sarcazmatic commented
В итоге помогли ребята с курса – замучился разбираться с автогенерацией ключей из таблиц.
Вопрос. Где почитать про ключи keyHolder и вот это и-фейс connection -> {
                PreparedStatement statement = connection.prepareStatement(sqlQueryPost, new String[]{"FILM_ID"});
                ...
                return statement;
            }, keyHolder)
Выглядит очень сложным. Что еще за стейтменты, как работает ифейс и как работает ки холдер.

2022-12-21 00:28 UTC, sarcazmatic commented
И да, прошлая версия была из вермишели собрана – пардона прошу, опирался только на то, что в курсе рассказывали. И очень торопился успеть в дл.

2022-12-21 17:42 UTC, Frilock requested changes
Евгений, уже лучше =)
По поводу тестов, видел Ваш комментарий про 300+ тестов. Мне кажется это перебор, важно ведь не количество, а качество.

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.CREATED)
Кажется, что ненормально такой статус возвращать. Разве нет? Ну то есть у вас ошибка, а вы шлете не ошибочный код

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Mpa mpa = new Mpa("NULL", 0);
А вот Mpa можно и не инициализировать

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final @NonNull String name;
Аннотации пишем на строке выше чем обьявляение переменной.
private final @NonNull String description;

Лучше
@NonNull 
private final String description

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public User(int id, String email, String login, String name, LocalDate birthday, List<User> friendship){
А почему AllArgsConstructor ставите?

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            } catch (NullPointerException e) {
А откуда в методе NPE? NPE не нужно ловить, их нужно не допускать. Кроме того, смотрите, бывают случаи, когда вы ловите какое то исключение, но в catch ничего не делаете. Тогда чтобы не было варнинга, вы называете его не e, а ignored
Относится ко всем похожим случаям в других методах

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public Mpa getMpaById(Integer id) {
Пропущен     @Override над методом

2022-12-21 17:42 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getName() == null || StringUtils.isBlank(user.getName())) {
user.getName() == null не нужна, она включена в isBlanl

2022-12-21 18:29 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.CREATED)
Ой, это вообще лишняя штука осталась. Удалил.

2022-12-21 18:43 UTC, sarcazmatic commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            } catch (NullPointerException e) {
Вспомнил про Optional и заменил)

2022-12-21 18:49 UTC, sarcazmatic commented
А 325 тестов – это которые Практикум дает в постман, чтобы проверить функционал приложения)

2022-12-22 06:12 UTC, Frilock approved these changes
Принято, к слову про ваш вопрос https://java-blog.ru/osnovy/preparedstatement, что то такое нашел, но я думаю есть довольно много ресурсов на английском. А вот в плане книжки не подскажу. Но на самом деле именно эти конструкции в реальных проектах мало используются. Дальше покажут вам что то по приятнее

2022-12-22 06:25 UTC, merged